name: ireng
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  google_fonts: ^6.1.0
  intl: ^0.19.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/logo_sapa_hebat_2.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "lib/assets/images/logo_sapa_hebat_2.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "lib/assets/images/logo_sapa_hebat_2.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
